apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etlnexus.fullname" . }}-backend-secret
  labels: {{- include "etlnexus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.backend.secretEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
