apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "etlnexus.fullname" . }}-backend
  labels:
    {{- include "etlnexus.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "etlnexus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "etlnexus.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- if .Values.imagePullSecret.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.imageRegistry }}/{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: {{ include "etlnexus.fullname" . }}-backend-config
            - secretRef:
                name: {{ include "etlnexus.fullname" . }}-backend-secret
          readinessProbe:
            httpGet: { path: /api/health, port: {{ .Values.backend.port }} }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /api/health, port: {{ .Values.backend.port }} }
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
